const carMakes: string[] = [
    "Toyota",
    "Ford",
    "BMW",
    "Skoda",
    "Seat",
    "Opel",
    "Mercedes-Benz",
    "Audi",
    "Volkswagen",
    "Honda",
    "Hyundai",
    "Nissan",
    "Chevrolet",
    "Kia",
    "Peugeot",
    "Renault",
    "Volvo",
    "Subaru",
    "Mazda",
    "Jaguar",
    "Land Rover",
    "Tesla",
    "Porsche",
    "Ferrari",
    "Lamborghini",
    "Mitsubishi",
    "Fiat",
    "Jeep",
    "Chrysler",
    "Dodge",
    "Alfa Romeo",
    "Suzuki",
  ];
  
  export default carMakes;